#!/bin/sh -e

case "$1" in
purge)
	for f in /usr/sbin/citidel* ; do
		[ -L $f ] && rm -rf $f
	done
  rm -rf /usr/lib/phalanx/*
  ;;

remove)
	for f in /usr/sbin/citidel* ; do
		[ -L $f ] && rm -rf $f
	done
  rm -rf /usr/lib/phalanx/*
  ;;

upgrade | deconfigure)
  #
  ;;

abort-upgrade | failed-upgrade)
  #
  ;;

*)
  echo "unknown argument --> $1" >&2
  exit 0
  ;;
esac
